simplemooc/courses/urls.py
from django.urls import path
from simplemooc.courses import views

app_name = 'courses'

urlpatterns = [
    path('', views.index, name='index'),
    # path('<int:pk>/', views.details, name='details'),
    path('<slug:slug>/', views.details, name='details'),
    path('<slug:slug>/inscricao/', views.enrollment, name='enrollment'),
    path('<slug:slug>/cancelar-inscricao/', views.undo_enrollment, name='undo_enrollment'),
    path('<slug:slug>/anuncios/', views.announcements, name='announcements'),
    path('<slug:slug>/anuncios/<int:pk>/', views.show_announcement, name='show_announcement'),
    path('<slug:slug>/aulas/', views.lessons, name='lessons'),
    path('<slug:slug>/aulas/<int:pk>/', views.lesson, name='lesson'),
    path('<slug:slug>/materiais/<int:pk>/', views.material, name='material'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    path('cursos/', include('simplemooc.courses.urls', namespace='courses')),
    path('forum/', include('simplemooc.forum.urls', namespace='forum')),
    path('admin/', admin.site.urls),
]

# Se estiver em debug...
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # ...a variável vai receber mais uma chamada de função que recebe primeiro uma configuração de URL...
    # que depois vai gerar uma 'view', que recebe uma 'url' que vai pegar o diretório base, e conforme o resto...
    # da 'url' que foi retornado, ele vai buscar o caminho do arquivo.
    # 'MEDIA_ROOT' será o diretório base para todos os arquivos de média de todos os 'Models'...
    # O 'upload_to' é o sufixo, assim o caminho final será o 'MEDIA_ROOT' + 'upload_to'.

# ^ - começo de uma string.
# $ - final de uma string.

simplemooc/courses/forms.py
from django import forms
# from django.core.mail import send_mail
from django.conf import settings

from simplemooc.core.mail import send_mail_template
from simplemooc.courses.models import Comment


class ContactCourse(forms.Form):
    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem/Dúvida', widget=forms.Textarea)

    def send_mail(self, course):
        # 'course' que está enviando o contato.
        subject = f'[{course}] Contato'
        context = {
            # Forma nomeada, dicionário.
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }
        template_name = 'courses/contact_email.html'

        # Chama função 'send_mail_template'.
        send_mail_template(
            # Passa o assunto.
            subject,
            # Passa o nome do 'template'.
            template_name,
            # Recebe o contexto como parâmetro, que tem o 'nome', 'e-mail' e a 'mensagem'.
            context,
            # Lista com os e-mails que serão enviados.
            [settings.CONTACT_EMAIL]
        )

    # # Envio antigo, sem o uso de 'template'.
    # def send_mail(self, course):
    #     subject = f'[{course}}] Contato'
    #     message = 'Nome: %(name)s;E-mail: %(email)s;%(message)s'
    #     context = {
    #        'name': self.cleaned_data['name'],
    #        'email': self.cleaned_data['email'],
    #        'message': self.cleaned_data['message'],
    #     }
    #     message = message % context
    #     send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [settings.CONTACT_EMAIL])


class CommentForm(forms.ModelForm):
    """
    Formulário para meu model.
    """

    class Meta:
        model = Comment
        fields = ['comment']

simplemooc/courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from simplemooc.courses.models import Course, Enrollment, Lesson, Material
from simplemooc.courses.forms import ContactCourse, CommentForm
from simplemooc.courses.decorators import enrollment_required


def index(request):
    """
    Retorna os objetos cadastrados no banco de dados.
    """
    courses = Course.objects.all()
    template_name = 'courses/index.html'
    # Dicionário passado no final.
    context = {'courses': courses}
    return render(request, template_name, context)


# def details(request, pk):
# 	"""
# 	Retorna a página do curso 'pk', caso não for encontrada, retorna uma página 404.
#
# 	:param pk: É o númeroda da página referente ao 'id' do curso do banco de dados.
# 	"""
# 	course = get_object_or_404(Course, pk=pk)
# 	context = {'course': course}
# 	template_name = 'courses/details.html'
# 	return render(request, template_name, context)


def details(request, slug):
    # Ao invés de passar o 'id', passa o 'slug'.
    course = get_object_or_404(Course, slug=slug)
    context = {}

    # Verifica se o método é um 'post' ou se é um método 'get'.
    if request.method == 'POST':
        # Se for 'post', ele recebe o dicionário com todos os campos submetido pelo usuário.
        form = ContactCourse(request.POST)

        if form.is_valid():
            # Se enviaro formulário com sucesso...
            context['is_valid'] = True
            form.send_mail(course)

            # Limpa o formulário.
            form = ContactCourse()
    else:
        # Caso contrário, ok.
        form = ContactCourse()

    # Variável form.
    context['form'] = form
    context['course'] = course
    template_name = 'courses/details.html'
    return render(request, template_name, context)


# 'decorator', que o próprio Django já disponibiliza, para obrigar o usuário
# a estar logado. Olha o 'request', vê se o usuário está autenticado, se estiver,
# ele executa normalmente, se não ele redireciona o usuário para uma página de 'login'.
@login_required
def enrollment(request, slug):
    # Pega o curso atual.
    course = get_object_or_404(Course, slug=slug)
    # Esse método vai ser passado um filtro, qual vai ser o 'user' do 'request.
    # Ele retorna uma 'tupla', a inscrição se ouver, caso não,
    # será criado, e um boleano dizendo se criou ou não.
    # Essa inscrição será do usuário atual, que está logado
    # no sistema, e vai ter o curso em questão.
    enrollment, created = Enrollment.objects.get_or_create(user=request.user, course=course)

    if created:
        # enrollment.active()
        # Função do modo 'messages' que já está disponível.
        messages.success(request, 'Você foi inscrito no curso com sucesso')
    else:
        messages.info(request, 'Você já está inscrito no curso')

    return redirect('accounts:dashboard')


@login_required
def undo_enrollment(request, slug):
    """
    Todas as páginas associadas ao curso está com 'slug', mas não necessariamente é preciso.
    Não tem a necessidade de ser uma 'url' descritiva, poderia ser coloca o 'id' da
    matrícula diretamente. Porém estamos deixando padrão com o 'slug' em todas.
    """
    course = get_object_or_404(Course, slug=slug)
    enrollment = get_object_or_404(Enrollment, user=request.user, course=course)

    if request.method == 'POST':
        enrollment.delete()
        messages.success(request, 'Sua inscrição foi cancelada com sucesso')
        return redirect('accounts:dashboard')

    template = 'courses/undo_enrollment.html'
    context = {
        'enrollment': enrollment,
        'course': course,
    }

    return render(request, template, context)


@login_required
@enrollment_required
def announcements(request, slug):
    # Busca o 'curso' do 'request'.
    course = request.course
    template = 'courses/announcements.html'
    context = {
        'course': course,
        # Todos os anúncios do curso estão nessa variável.
        'announcements': course.announcements.all()
    }
    return render(request, template, context)


@login_required
@enrollment_required
def show_announcement(request, slug, pk):
    course = request.course  # Busca o 'curso' do 'request'.
    announcement = get_object_or_404(course.announcements.all(), pk=pk)
    form = CommentForm(request.POST or None)

    if form.is_valid():
        # Cria e salva o comentário.
        comment = form.save(commit=False)

        # Usuário logado.
        comment.user = request.user

        # O anúncio 'announcement = get_object_or_404(course.announcements.all(), pk=pk)'.
        comment.announcement = announcement

        # Depois chama o 'comment.save()' para de fato salvar o comentário.
        comment.save()

        # Apenas para zerar o formulário.
        form = CommentForm()
        messages.success(request, 'Seu comentário foi enviado com sucesso')

    template = 'courses/show_announcement.html'
    context = {
        'course': course,
        'announcement': announcement,
        'form': form,
    }
    return render(request, template, context)


@login_required
@enrollment_required
def lessons(request, slug):
    course = request.course
    template = 'courses/lessons.html'
    lessons = course.release_lessons()

    if request.user.is_staff:
        lessons = course.lessons.all()

    context = {
        'course': course,
        'lessons': lessons
    }
    return render(request, template, context)


@login_required
@enrollment_required
def lesson(request, slug, pk):
    course = request.course
    # 'course=course' garantia de que as aulas são mesmo desse curso.
    lesson = get_object_or_404(Lesson, pk=pk, course=course)

    # Verificação básica de segurança.
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Esta aula não está disponível')
        return redirect('courses:lessons', slug=course.slug)

    template = 'courses/lesson.html'
    context = {
        'course': course,
        'lesson': lesson
    }
    return render(request, template, context)


@login_required
@enrollment_required
def material(request, slug, pk):
    course = request.course
    # Não tem relacionamento com o curso, mas tem relacionamento com a aula
    # que tem relacionamento com o curso. Quando coloca dois underscore '__'
    # vou acessar uma propriedade já do outro objeto 'lesson__course'.
    material = get_object_or_404(Material, pk=pk, lesson__course=course)
    lesson = material.lesson

    # Verificação básica de segurança.
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Este material não está disponível')
        return redirect('courses:lesson', slug=course.slug, pk=lesson.pk)

    # Verifica se o usuário é 'is_embedded', se não for ele redireciona
    # para 'material.file.url', se for ele exibe realmente o template.
    if not material.is_embedded():
        return redirect(material.file.url)

    template = 'courses/material.html'
    context = {
        'course': course,
        'lesson': lesson,
        'material': material
    }
    return render(request, template, context)

simplemooc/courses/templates/courses/announcement_mail.html
{{ announcement.content|linebreaks }}

simplemooc/courses/templates/courses/announcements.html
{% extends "courses/course_dashboard.html" %}

{% block dashboard_content %}
{% for announcement in announcements %}
<div class="well">
    <h2>
        <a href="{% url 'courses:show_announcement' course.slug announcement.pk %}">{{ announcement.title }}</a>
    </h2>
    {{ announcement.content|linebreaks }}
    <p>
        <a href="{% url 'courses:show_announcement' course.slug announcement.pk %}#comments">
        <i class="fa fa-comments-o"></i>
        {% with comments_count=announcement.comments.count %}   {# armazena uma variável mais 'complexa' em uma mais 'simples', para evitar sua repetoção, a variável criada fica disponível apenas dentro desse 'with'. #}
        {{ comments_count }}       {# mostra apenas a contagem de comentários. #}
        Comentário{{ comments_count|pluralize }}        {# template tag 'pluralize', se for 0 ou mais de 1 ele vai jogar um 's' se for 1 ele mantem intácto por padrão. #}
        {% endwith %}
        </a>
    </p>
</div>
{% empty %}     {# quando não houver nenhum valor nesse 'for', vai renderizar o 'empty'. #}
<div class="well">
    <h2>Nenhum anúncio criado</h2>
</div>
{% endfor %}
{% endblock %}

simplemooc/courses/templates/courses/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

simplemooc/courses/templates/courses/course_dashboard.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:announcements' course.slug %}">{{ course }}</a></li>
{% endblock %}

{% block menu_options %}
<li class="pure-menu-heading">
    {{ course }}
</li>
<li>
    <a href="{% url 'courses:lessons' course.slug %}">      {# Lembrando: todo template que usar 'course_dashboard' tem que ter 'course.slug'. #}
        <i class="fa fa-video-camera"></i>
        Aulas e Materiais
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-info-circle"></i>
        Informações
    </a>
</li>
<li>
    <a href="{% url 'courses:announcements' course.slug %}">
        <i class="fa fa-envelope"></i>
        Anúncios
    </a>
</li>
<li>
    <a href="{% url 'forum:index' %}">
        <i class="fa fa-comments"></i>
        Fórum de Dúvidas
    </a>
</li>
{{ block.super }}
{% endblock %}

simplemooc/courses/templates/courses/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                    <a href="{% url 'courses:enrollment' course.slug %}" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre o Curso</h4>
            {{ course.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="" />
            {% endif %}
            <h4>Dúvidas?</h4>
            <p>
                <a href="#contato" title="" class="pure-button">Fale Conosco</a>
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-1">
        <h3>Tire sua dúvida sobre o Curso</h3>
        {% if is_valid %}
        <p>Você enviou o formulário com sucesso</p>
        {% endif %}
        <form action="#contato" class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}    {# todo 'post' que for para o servidor Django, ele válida para saber se realmente o usuário é confiável, e não um post de outro lugar. #}
            <fieldset>
                {% for field in form %}     {# para cada campo do formulário... #}
                <div class="pure-control-group">
                    {{ field.label_tag }}   {# renderize a tag do label... #}
                    {{ field }}     {# renderize o campo #}
                    {% if field.errors %}   {# se tiver erro... #}
                    <ul class="errorlist">
                        {% for error in field.errors %}     {# para cada erro... #}
                        <li>{{ error }}</li>    {# imprime o erro. #}
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

simplemooc/courses/templates/courses/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
            <p>Abaixo a lista de cursos disponíveis na plataforma</p>
        </div>
    </div>
</div>
{% for course in courses %}     {# for para cada curso dentro da váriavel 'courses', joga dentro de 'course'. #}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <a href="{{ course.get_absolute_url }}">    {# 'href=' retorna a 'url' do curso. #}
            {% if course.image %}      {# se houver alguma imagem... #}
            <img src="{{ course.image.url }}" alt="{{ course.name }}" />
            {% else %}      {# caso não for verdadeiro. #}
            <img src="{% static 'img/course-image.png' %}" alt="{{ course.name }}" />
            {% endif %}
            </a>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead"><a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a></h4>     {# 'href=' retorna a 'url' do curso. #}
            {{ course.description|linebreaks }}     {# mostra a descrição dos cursos, busca no banco de dados, 'linebreaks é um filtro do Django. #}
        </div>
    </div>
</div>
{% empty %}     {# opção do for que mostra o que está definido quando não houver nenhum valor. #}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <p>Nenhum curso está disponíveis na plataforma.</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

simplemooc/courses/templates/courses/lesson.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
{% endblock %}

{% block dashboard_content %}
<div class="well">
    <h2><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
	{{ lesson.description|linebreaks }}
    <p>
        <h4>Material da Aula</h4>
        <table class="pure-table full">
            <thead>
                <tr>
                    <th>
                        Nome
                    </th>
                    <th>
                        Ação
                    </th>
                </tr>
            </thead>
            <tbody>
            	{% for material in lesson.materials.all %}
                <tr class="{% cycle '' 'pure-table-odd' %}">	{# tabela zebrada, uma hora retorna 'vazio', outra hora retorna o 'pure-table-odd'. #}
                    <td>
                        {{ material }}
                    </td>
                    <td>
                    	{% if material.is_embedded %}
                        <a href="{% url 'courses:material' course.slug material.pk %}">
                            <i class"fa fa-video-camera"></i>
                            Acessar
                        </a>
                        {% else %}
		                <a target="_blank" href="{{ material.file.url }}">
		                    <i class"fa fa-download"></i>
		                    Baixar
		                </a>
                        {% endif %}
                    </td>
                </tr>
				{% endfor %}
            </tbody>
        </table>
    </p>
</div>
{% endblock %}

simplemooc/courses/templates/courses/lessons.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
{% endblock %}

{% block dashboard_content %}
{% for lesson in lessons %}
<div class="well">
    <h2><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    <p>
        {{ lesson.description|truncatewords:'20' }} {# recebe como argumento o número de palavras que quero exibir, e após isso ele coloca "..." #}
        <br />
        <a href="{% url 'courses:lesson' course.slug lesson.pk %}" title="">
        <i class="fa fa-eye"></i>
        Acessar Aula
        </a>
    </p>
</div>
{% empty %}
<div class="well">
    <h2>
        Nenhuma aula disponível.
    </h2>
</div>
{% endfor %}
{% endblock %}

simplemooc/courses/templates/courses/material.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a></li>
{% endblock %}

{% block dashboard_content %}

<div class="well">
    <h2><a href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a></h2>
    {{ material.embedded|safe }}	{# 'safe' filtro que diz para o Django que o conteúdo é seguro. #}
    <p>
        <a href="{% url 'courses:lesson' course.slug lesson.pk %}">Voltar</a>
    </p>
</div>
{% endblock %}

simplemooc/courses/templates/courses/show_announcement.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:show_announcement' course.slug announcement.pk %}">{{ announcement }}</a></li>
{% endblock %}

{% block dashboard_content %}
    <div class="well">
        <h2>{{ announcement.title }}</h2>
        {{ announcement.content|linebreaks }}
    </div>
    <div class="well">
        <h4 id="comments">Comentários
        <a class="fright" href="#add_comment">Comentar</a></h4>
        <hr />
        {% for comment in announcement.comments.all %}  {# para cada comentário no anúncio, esse 'comments' é a 'related_name' no 'models'. #}
        <p>
            <strong>{{ comment.user }}</strong> disse à {{ comment.created_at|timesince }} atrás: <br />
            {{ comment.comment|linebreaksbr }}
        </p>
        <hr>
        {% empty %}
        <p>
            Nenhum comentário para este anúncio.
        </p>
        {% endfor %}
        <form method="post" class="pure-form pure-form-stacked" id="add_comment">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

simplemooc/courses/templates/courses/undo_enrollment.html
{% extends "courses/course_dashboard.html" %}

{% block dashboard_content %}
<form action="" method="post">
	{% csrf_token %}
	<h3>Você deseja realmente cancelar a inscrição deste curso?</h3>
	<div class="pure-controls">
		<button type="submit" class="pure-button pure-button-primary">Confirmar</button>
		<a href="{% url 'courses:announcements' course.slug %}" class="pure-button">Voltar</a>
	</div>
</form>
{% endblock %}