simplemooc/accounts/urls.py
from django.urls import path

# Alterar o nome para evitar conflito de 'views'.
# from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from simplemooc.accounts import views

app_name = 'accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    # Ao invés de criar minha própria 'view', estou colocando uma 'view' direto do Django.
    # 3ª Parâmetro que é um dicionário, serve para parâmetros nomeados,
    # que serão passados para essa 'view'. Faz a substituição na 'view'.
    path('entrar/', LoginView.as_view(template_name='accounts/login.html'), name='login'),

    # Vai ser redirecionado para a 'view' 'home', da 'app' 'core'.
    path('sair/', LogoutView.as_view(next_page='core:home'), name='logout'),
    path('cadastre-se/', views.register, name='register'),
    path('nova-senha/', views.password_reset, name='password_reset'),
    path('confirmar-nova-senha/<slug:key>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('editar/', views.edit, name='edit'),
    path('editar-senha/', views.edit_password, name='edit_password'),
]

simplemooc/core/urls.py
from django.urls import path
from simplemooc.core import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('contato/', views.contact, name='contact'),
]

simplemooc/forum/urls.py
from django.urls import path
from simplemooc.forum import views

app_name = 'forum'

urlpatterns = [
    path('', views.index, name='index'),
    path('tag/<slug:tag>/', views.index, name='index_tagged'),  # duas 'urls' para a mesma 'view'.
    path('respostas/<int:pk>/correta/', views.reply_correct, name='reply_correct'),
    path('respostas/<int:pk>/incorreta/', views.reply_incorrect, name='reply_incorrect'),
    path('<slug:slug>/', views.thread, name='thread'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    path('cursos/', include('simplemooc.courses.urls', namespace='courses')),
    path('forum/', include('simplemooc.forum.urls', namespace='forum')),
    path('admin/', admin.site.urls),
]

# Se estiver em debug...
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # ...a variável vai receber mais uma chamada de função que recebe primeiro uma configuração de URL...
    # que depois vai gerar uma 'view', que recebe uma 'url' que vai pegar o diretório base, e conforme o resto...
    # da 'url' que foi retornado, ele vai buscar o caminho do arquivo.
    # 'MEDIA_ROOT' será o diretório base para todos os arquivos de média de todos os 'Models'...
    # O 'upload_to' é o sufixo, assim o caminho final será o 'MEDIA_ROOT' + 'upload_to'.

# ^ - começo de uma string.
# $ - final de uma string.

simplemooc/core/models.py
# from django.db import models
#
# # Create your models here.

simplemooc/core/views.py
from django.shortcuts import render


def home(request):
    """
    1º parâmetro é o 'request'.
    2º parâmetro 'home.html', é o nome do template.
    3º parâmetro passei um dicionário que são as variaveis que ficaram disponiveis no template.
    """
    return render(request, 'home.html')


def contact(request):
    return render(request, 'contact.html')

simplemooc/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>Simple MOOC</title>

    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/pure-min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<body>
<div class="header">
    <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="{% url 'core:home' %}">SIMPLE MOOC</a>
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="{% url 'courses:index' %}">Cursos</a></li>
            <li><a href="{% url 'forum:index' %}">Fórum</a></li>
            <li><a href="{% url 'core:contact' %}">Contato</a></li>
            {% if user.is_authenticated %}      {# se o usuário estiver autenticado... #}
            <li><a href="{% url 'accounts:dashboard' %}">Painel</a></li>
            <li><a href="{% url 'accounts:logout' %}">Sair</a></li>     {# vai ter a opção de sair. #}
            {% else %}      {# se ele não estiver autenticado... #}
            <li><a href="{% url 'accounts:login' %}">Entrar</a></li>    {# vai ter a opção de logar. #}
            {% endif %}
        </ul>
    </div>
</div>
<div class="content">
    {% if messages %}
    <div class="pure-g-r content-ribbon">
        <aside class="pure-u-1">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </aside>
    </div>
    {% endif %}
    {% block content %}{% endblock %} {# conteúdo que será colocado. #}
    <div class="footer">
        Copyright &copy 2018 - <a href="https://wesleymendes.com.br" class="mylink-color" target="_blank">Wesley Mendes</a> | Simple MOOC - Uma simples plataforma de ensino a distância
    </div>
</div>
<script src="{% static 'js/yui-min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
{% block scripts %}{% endblock %}        {# bloco de 'scripts' #}
</body>
</html>

simplemooc/core/templates/contact.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h1>Fale conosco</h1>
        <p>Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</p>
        <h4>Links</h4>
        <ul>
            <li><i class="fab fa-github"></i> <a href="https://github.com/WesGtoX" target="_blank">WesGtoX</a></li>
            <li><i class="fab fa-linkedin-in"></i> <a href="https://www.linkedin.com/in/wesgtox/" target="_blank">Wesley Mendes</a></li>
            <li><i class="fas fa-envelope"></i> <a href="mailto:wesley@wesleymendes.com.br"></i>wesley@wesleymendes.com.br</a></li>
            <li><i class="fab fa-twitter"></i> <a href="https://twitter.com/wesgtox" target="_blank">@wesgtox</a></li>
        </ul>
    </div>
</div>
{% endblock %}

simplemooc/core/templates/home.html
{% extends "base.html" %} {# diz que o conteúdo estende do 'base.html'. #}

{% load static %}

{% block content %} {# template tag que vem com Django, indica onde será colocado, delimita até o {% endblock %}. #}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    Uma Simples Plataforma de Ensino a Distância
                </h1>
                <h2 class="splash-subhead">
                    O Simple MOOC visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
                </h2>
                <p>
                    <a href="#" class="pure-button primary-button">Saiba mais</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
            <h3>Publique suas aulas</h3>
            <p>
                O Simple MOOC tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
            </p>
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="{% static 'img/video-aulas-materiais.png' %}" alt="Vídeo aulas e materiais digitais." width="450px">
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="{% static 'img/forum-duvidas.png' %}" alt="Fórum de Dúvidas" width="450px">
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Fórum de Dúvidas</h4>
            <h3>Interaja com seus Alunos</h3>
            <p>
                No Simple MOOC você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Exercícios</h4>
            <h3>Crie exercícios para avaliar seus alunos</h3>
            <p>
                Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
            </p>
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="{% static 'img/exercicios.png' %}" alt="Exercícios" width="450px">
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="{% static 'img/mural-avisos.png' %}" alt="Mural de Avisos" width="450px">
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Mural de Avisos</h4>
            <h3>Envie anúncios diretamente para os alunos</h3>
            <p>
                Organize os avisos do seu curso de forma fácil e simples.
            </p>
        </div>
    </div>
</div>
{% endblock %}