simplemooc/accounts/urls.py
from django.urls import path

# Alterar o nome para evitar conflito de 'views'.
# from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from simplemooc.accounts import views

app_name = 'accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    # Ao invés de criar minha própria 'view', estou colocando uma 'view' direto do Django.
    # 3ª Parâmetro que é um dicionário, serve para parâmetros nomeados,
    # que serão passados para essa 'view'. Faz a substituição na 'view'.
    path('entrar/', LoginView.as_view(template_name='accounts/login.html'), name='login'),

    # Vai ser redirecionado para a 'view' 'home', da 'app' 'core'.
    path('sair/', LogoutView.as_view(next_page='core:home'), name='logout'),
    path('cadastre-se/', views.register, name='register'),
    path('nova-senha/', views.password_reset, name='password_reset'),
    path('confirmar-nova-senha/<slug:key>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('editar/', views.edit, name='edit'),
    path('editar-senha/', views.edit_password, name='edit_password'),
]

simplemooc/courses/urls.py
from django.urls import path
from simplemooc.courses import views

app_name = 'courses'

urlpatterns = [
    path('', views.index, name='index'),
    # path('<int:pk>/', views.details, name='details'),
    path('<slug:slug>/', views.details, name='details'),
    path('<slug:slug>/inscricao/', views.enrollment, name='enrollment'),
    path('<slug:slug>/cancelar-inscricao/', views.undo_enrollment, name='undo_enrollment'),
    path('<slug:slug>/anuncios/', views.announcements, name='announcements'),
    path('<slug:slug>/anuncios/<int:pk>/', views.show_announcement, name='show_announcement'),
    path('<slug:slug>/aulas/', views.lessons, name='lessons'),
    path('<slug:slug>/aulas/<int:pk>/', views.lesson, name='lesson'),
    path('<slug:slug>/materiais/<int:pk>/', views.material, name='material'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    path('cursos/', include('simplemooc.courses.urls', namespace='courses')),
    path('forum/', include('simplemooc.forum.urls', namespace='forum')),
    path('admin/', admin.site.urls),
]

# Se estiver em debug...
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # ...a variável vai receber mais uma chamada de função que recebe primeiro uma configuração de URL...
    # que depois vai gerar uma 'view', que recebe uma 'url' que vai pegar o diretório base, e conforme o resto...
    # da 'url' que foi retornado, ele vai buscar o caminho do arquivo.
    # 'MEDIA_ROOT' será o diretório base para todos os arquivos de média de todos os 'Models'...
    # O 'upload_to' é o sufixo, assim o caminho final será o 'MEDIA_ROOT' + 'upload_to'.

# ^ - começo de uma string.
# $ - final de uma string.

simplemooc/accounts/models.py
import re

from django.db import models
from django.core import validators

from django.conf import settings
from django.contrib.auth.models import (
    AbstractBaseUser, PermissionsMixin, UserManager
)


class User(AbstractBaseUser, PermissionsMixin):
    # Nome de usuário padrão, que também é único.
    username = models.CharField(
        'Nome de Usuário', max_length=30, unique=True,
        # Valida se o nome de usuário recebeu os caracteres permitidos.
        validators=[validators.RegexValidator(
            re.compile('^[\w.@+-]+$'),
            'O nome de usuário só pode conter letras, dígitos ou os seguintes caracteres: @/./+/-/_', 'invalid'
        )]
    )
    # E-mail que nesse caso é único, é a grande diferença para o do Django.
    email = models.EmailField('E-mail', unique=True)
    # Campo do nome completo que vai ser opcional, ao invés de 'first_name' e 'last_name'.
    name = models.CharField('Nome', max_length=100, blank=True)
    # Vai verificar se o usuário está ativo e para logar, por padrão é 'True'.
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    # Para o Django 'admin' saber se ele pode acessar a área administrativa,
    # se é da equipe administrativa, por padrão é 'False'.
    is_staff = models.BooleanField('É da equipe?', blank=True, default=False)
    # Essa data é importante na criação do 'superuser', é uma recomendação para ser compatível com a 'app' Django.
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    # O 'manager' que tem algumas coisas úteis para nós.
    objects = UserManager()

    # Para ser compátivel com alguns comandos e algumas outras coisas do Django, 'app' de usuário.
    # Indica o campo que é único e vai ser a referência na hora do 'login'.
    # Por padrão é 'login', poderia ser o 'email'.
    USERNAME_FIELD = 'username'

    # Utilizado no comando de criação 'superusuario', vai utilizar esse comando porque vai precisar
    # apagar o banco de dados, e vamos criar outro usuário atráves desse comando.
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        """
        Esse método é a representação do 'skin' do usuário.

        Se tiver 'name', retorna o nome, caso contrário retorna o 'username'.
        """
        return self.name or self.username

    def get_short_name(self):
        """
        A 'app' de usuário de Django também pega as implementações de alguns métodos,
        não é obrigatório, mas é interessante para funcionamento do 'admin'.

        :self.username: descrição curta do nome.
        """
        return self.username

    def get_full_name(self):
        """
        O 'fullname' é a representação 'string' do próprio objeto.
        """
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'


class PasswordReset(models.Model):
    """
    Esse 'model' tem um relacionamento de 'n' para '1' com o usuário,
    o usuário pode ter um ou mais 'PasswordReset'.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Usuário',
        # 'on_delete' é obrigatório no Django 2.0.
        related_name='resets', on_delete=models.CASCADE
    )
    key = models.CharField('Chave', max_length=100, unique=True)

    # Vou permitir que esse usuário clique nesse 'link' randômico, em no máximo 2 horas.
    created_at = models.DateTimeField('Criado em', auto_now_add=True)

    # Vai indicar se o 'link' foi usado.
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova Senha'
        verbose_name_plural = 'Novas Senhas'
        # Parâmetro da classe 'Meta' do 'model' que pode indicar qual o ordenamento,
        # uma lista de atributos do 'model', que servirão para ordenamento padrão, default.
        ordering = ['-created_at']

simplemooc/accounts/forms.py
from django import forms
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from simplemooc.core.mail import send_mail_template
from simplemooc.core.utils import generate_hash_key

from .models import PasswordReset

# Indica que estamos usando o 'user' que o Django reconhece
# como usuário do sistema que no nosso caso é o 'CustomUser'.
User = get_user_model()


# Não vai ser um 'ModelForm' porque ele não vai estar associado a
# nenhum model inicialmente. Porque só queremos um campo de e-mail.
class PasswordResetForm(forms.Form):
    email = forms.EmailField(label='E-mail')

    # Para validar se o 'email' é de algum usuário do sistema.
    def clean_email(self):
        email = self.cleaned_data['email']

        # Detectar se existem algum usuário do sistema, retorna um boleano.
        if User.objects.filter(email=email).exists():
            # TODO: 'clean_...' retorna o valor que o formulátio vai pegar no final.
            return email

        raise forms.ValidationError('Nenhum usuário encontrado com este e-mail')

    def save(self, base_domain=None):
        # Quando for válido, eu busco o usuário com aquele e-mail.
        user = User.objects.get(email=self.cleaned_data['email'])

        # Gera a chave.
        key = generate_hash_key(user.username)

        # Cria o 'model' para resetar a senha.
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'accounts/password_reset_mail.html'

        # Assunto.
        subject = 'Criar nova senha no Simple MOOC'
        context = {
            'reset': reset,
            'base_domain': base_domain
        }

        # Função criada de envio de 'email' no 'core'.
        send_mail_template(subject, template_name, context, [user.email])


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmação de Senha', widget=forms.PasswordInput)

    def clean_password2(self):
        """
        Esse método vai ser para a senha 2.
        """
        # Pega a senha 1...
        password1 = self.cleaned_data.get("password1")

        # ...pega a senha 2...
        password2 = self.cleaned_data.get("password2")

        # ...verifica se foram enviadas, e depois se são iguais.
        if password1 and password2 and password1 != password2:
            # Se elas não forem iguais mostra uma mensagem de erro.
            raise forms.ValidationError('A confirmação não está correta')

        return password2

    def save(self, commit=True):
        """
        Novo método 'save' que substitui o do 'UserCreationForm'.
        Ele recebe o 'commit' igual a 'True', chama o 'save' do
        meu 'super' que no caso é 'UserCreationForm'.
        """
        # No 'UserCreationForm' ele chama o 'save' do 'ModelForm' através do 'super'.
        # Chama o 'save' passa o 'commit=False' para não salvar, vai pegar usuário,
        # vai setar a senha. Como também foi passado 'commit=False', ele não vai salvar
        # o usuário, ele vai retornar o usuário.
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])  # seta a senha...

        # Da uma possibilidade de se quiser herdar e fazer outro 'registerForm', pode chamar parte desse
        # 'commit' e não salvar na hora, posso querer alterar alguma coisa do usuário antes de salvar.
        if commit:
            user.save()

        # O padrão de 'ModelForm' é sempre o 'save' retornar a instância do objeto relacionado.
        return user

    class Meta:
        model = User
        # No formulário de registro vai precisar apenas do 'username' e 'email'.
        fields = ['username', 'email']


class EditAccountForm(forms.ModelForm):
    class Meta:
        # Para saber qual 'model' que o formulário vai precisar...
        model = User
        # Campos modificados para os que criamos.
        fields = ['username', 'email', 'name']

simplemooc/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404

# from django.conf import settings
from django.core.mail import mail_admins
from django.template.loader import render_to_string

from django.contrib import messages
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib.auth.decorators import login_required

# from simplemooc.core.utils import generate_hash_key
# from simplemooc.courses.models import Enrollment

from simplemooc.accounts.forms import RegisterForm, EditAccountForm, PasswordResetForm
from simplemooc.accounts.models import PasswordReset

User = get_user_model()


# Essa função é chamada passando como primeiro parâmetro,
# a função que vai ser executada, verifica se o usuário está logado,
# se estiver ok, se não estiver ele faz um 'redirect' para a página de 'login',
# colocando um parêmetro na 'url' o 'next'.
@login_required
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    context = {}
    return render(request, template_name, context)


def admin_mail_send(user):
    data = {
        'name': user.name,
        'username': user.username,
        'email': user.email
    }

    plain_text = render_to_string('accounts/emails/new_user.txt', data)
    html_email = render_to_string('accounts/emails/new_user.html', data)

    mail_admins(
        subject='Novo usuário cadastrado',
        message=plain_text,
        html_message=html_email,
        fail_silently=False
    )


def register(request):
    template_name = 'accounts/register.html'
    # Verifica se o método é 'post'...
    if request.method == 'POST':
        # ...se for 'post', vou pegar o formulário...
        form = RegisterForm(request.POST)

        if form.is_valid():
            # ...e salvar o usuário. # 'form.save()' vai retornar o usuário.
            user = form.save()

            # A senha não está em 'user.password', 'user.password' é uma senha
            # 'criptografada', que é a senha que vai para o banco de dados.
            user = authenticate(username=user.username, password=form.cleaned_data['password1'])

            # É responsável por logar de fato o usuário, coloca o usuário na sessão.
            login(request, user)

            # enviar email de criação de usuário para os admins
            admin_mail_send(user=user)

            # Depois faz o 'redirect' para a 'home'.
            return redirect('core:home')
    else:
        form = RegisterForm()

    context = {'form': form}

    return render(request, template_name, context)


def password_reset(request):
    template_name = 'accounts/password_reset.html'
    context = {}

    # Forma mais prática para que os dados não sejam validados, quando for 'POST'
    # de fato ele vai validar os dados, e quando não for, não vai ser validado.
    form = PasswordResetForm(request.POST or None)

    base_domain = request.build_absolute_uri('/')[:-1]

    if form.is_valid():
        form.save(base_domain)
        # Exibe a mensagem de erro.
        context['success'] = True

    context['form'] = form
    return render(request, template_name, context)


def password_reset_confirm(request, key):
    """
    Pega a chave que está na 'url', busca o 'model', deu tudo ok, passou, não deu 'erro 404'...
    """
    template_name = 'accounts/password_reset_confirm.html'
    context = {}

    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)

    if form.is_valid():
        form.save()
        context['success'] = True

    context['form'] = form
    return render(request, template_name, context)


@login_required
def edit(request):
    template_name = 'accounts/edit.html'
    # Dicionário.
    context = {}

    # Verifica se o método é 'POST'.
    if request.method == 'POST':
        # Se for 'POST' chama o 'EditAccountForm', passando o 'POST' que são os dados.
        # 'instance' é a instância que está sendo alterada, o 'model',
        # que é o 'request.user', usuário atual da sessão.
        form = EditAccountForm(request.POST, instance=request.user)
        # Se o 'form' estiver válido...
        if form.is_valid():
            # ...ele salva.
            form.save()
            messages.success(request, 'Os dados da sua conta foram alterados com sucesso')
            return redirect('accounts:dashboard')
            # # Cria novamente um usuário vazio.
            # form = EditAccountForm(instance=request.user)
            # # E faz uma variável de 'sucesso', para apenas no template jogar um 'if' e jogar uma mensagem lá.
            # context['success'] = True
    else:
        # Se não for 'POST', é apenas um formulário vazio.
        form = EditAccountForm(instance=request.user)

    # Renderiza apenas o template com esse formulário
    context['form'] = form
    return render(request, template_name, context)


@login_required
def edit_password(request):
    template_name = 'accounts/edit_password.html'
    context = {}

    if request.method == 'POST':
        # Foi passado parâmetros nomeados porque esse 'form' é um pouco customizado,
        form = PasswordChangeForm(data=request.POST, user=request.user)

        # Então além dos parâmetros normais de um 'form' qualquer, ele recebe esse
        # parêmetro 'user', e como não sei qual a ordem deles, então passa nomeado.
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = PasswordChangeForm(user=request.user)

    context['form'] = form
    return render(request, template_name, context)

simplemooc/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

{% load courses_tags %}     {# carrega as 'tags' presentes em 'courses_tags' o Django sabe que é uma 'template tag' porque o arquivo está dentro de uma pasta chamada 'templatetags' que é o padrão. #}

{% block content %}
{% load_my_courses user as enrollments %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
        	{% block breadcrumb %}		{# herança de herança, template que herda de outro template. #}
            <li><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
            {% endblock %}
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Bem-vindo, {{ user }}
                </li>
                {% block menu_options %} 
                <li class="pure-menu-heading">Cursos</li>
                {% for enrollment in enrollments %}
                <li>
                    <a href="{% url 'courses:announcements' enrollment.course.slug %}">
                    <i class="fa fa-book"></i>
                    {{ enrollment.course }}
                    </a>
                </li>
                {% empty %}
                <li class="pure-menu-none">Nenhum curso encontrado</li>
                {% endfor %}
                <li class="pure-menu-heading">Configurações de Conta</li>
                <li>
                    <a href="{% url 'accounts:edit' %}">
                    <i class="fa fa-cog"></i>
                    Editar Informações
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:edit_password' %}">
                    <i class="fa fa-lock"></i>
                    Editar Senha
                    </a>
                </li>
                {% endblock %}
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
        	{% block dashboard_content %}
            <h2>Meus Cursos</h2>
            {% for enrollment in enrollments %}
            <div class="well">
                <h3>{{ enrollment.course }}
                ({{ enrollment.course.start_date|date:'d/m/Y'|default:'Sem data' }})   {# filtro aninhado, filtro em cima de filtro. #}
                </h3>
                {{ enrollment.course.description|linebreaks }}
                <div class="pure-controls">
                    <a href="{% url 'courses:announcements' enrollment.course.slug %}" class="pure-button pure-button-primary">Acessar</a>
                    <a href="{% url 'courses:undo_enrollment' enrollment.course.slug %}" class="pure-button button-error">Cancelar</a>
                </div>
            </div>
            {% empty %}
            <aside class="pure-u-1">
                <p>Nenhum curso inscrito</p>
            </aside>
            {% endfor %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}	{# chama o bloco da herança. #}
	{{ block.super }}	{# a variável 'block' é o bloco que está utilizando a 'tag' 'breadcrumb', ele tem um atributo chamado 'super', que chama o conteúdo que estava nele por padrão. #}
	<li>/</li>
	<li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method='POST'>
	{% csrf_token %}
    
{#	{% if success %} #}
{#	<p>Os dados foram alterados com sucesso</p> #}
{#	{% endif %} #}
{#    <fieldset> #}
    	{{ form.non_field_errors }}
    	{% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Salvar Modificações</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}	{# chama o bloco da herança. #}
	{{ block.super }}	{# a variável 'block' é o bloco que está utilizando a 'tag' 'breadcrumb', ele tem um atributo chamado 'super', que chama o conteúdo que estava nele por padrão. #}
	<li>/</li>
	<li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method='POST'>
	{% csrf_token %}
	{% if success %}
	<p>A sua senha foi alterada com sucesso</p>
	{% endif %}
    <fieldset>
    	{{ form.non_field_errors }}
    	{% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Alterar Senha</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/login.html
{% extends "base.html"%}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}      {# que são erros gerais, que não estão ligadas necessariamente a um campo, pode ser mais de um campo. #}

                {% for field in form %}     {# para cada campo no formulário (o 'form' é da 'view' do Django). #}
                <div class="pure-control-group">
                    {{ field.label_tag }}   {# 'view' do Django. #}
                    {{ field }}             {# 'view' do Django. #}
                    {{ field.errors }}      {# 'view' do Django. #}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="{% url 'accounts:password_reset' %}" title="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
    	{% if success %}
    	<p>Um e-mail foi enviado para você com mais detalhes de como criar uma nova senha</p>
    	{% else %}
        <h2>Informe seu E-mail</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}      {# que são erros gerais, que não estão ligadas necessariamente a um campo, pode ser mais de um campo. #}

                {% for field in form %}     {# para cada campo no formulário (o 'form' é da 'view' do Django). #}
                <div class="pure-control-group">
                    {{ field.label_tag }}   {# 'view' do Django. #}
                    {{ field }}             {# 'view' do Django. #}
                    {{ field.errors }}      {# 'view' do Django. #}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar E-mail</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
    	{% if success %}
    	<p>Sua senha foi criada com sucesso</p>
    	{% else %}
        <h2>Informe sua nova Senha</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}      {# que são erros gerais, que não estão ligadas necessariamente a um campo, pode ser mais de um campo. #}

                {% for field in form %}     {# para cada campo no formulário (o 'form' é da 'view' do Django). #}
                <div class="pure-control-group">
                    {{ field.label_tag }}   {# 'view' do Django. #}
                    {{ field }}             {# 'view' do Django. #}
                    {{ field.errors }}      {# 'view' do Django. #}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_mail.html
<p>
    Para criar uma nova senha, acesse o link:
    <a href="{{ base_domain }}{% url 'accounts:password_reset_confirm' reset.key %}" title="Link para Criar Nova Senha">
        Criar Nova Senha
    </a>
</p>

simplemooc/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}      {# que são erros gerais, que não estão ligadas necessariamente a um campo, pode ser mais de um campo. #}

                {% for field in form %}     {# para cada campo no formulário (o 'form' é da 'view' do Django). #}
                <div class="pure-control-group">
                    {{ field.label_tag }}   {# 'view' do Django. #}
                    {{ field }}             {# 'view' do Django. #}
                    {{ field.errors }}      {# 'view' do Django. #}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}