simplemooc/core/urls.py
from django.urls import path
from simplemooc.core import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('contato/', views.contact, name='contact'),
]

simplemooc/forum/urls.py
from django.urls import path
from simplemooc.forum import views

app_name = 'forum'

urlpatterns = [
    path('', views.index, name='index'),
    path('tag/<slug:tag>/', views.index, name='index_tagged'),  # duas 'urls' para a mesma 'view'.
    path('respostas/<int:pk>/correta/', views.reply_correct, name='reply_correct'),
    path('respostas/<int:pk>/incorreta/', views.reply_incorrect, name='reply_incorrect'),
    path('<slug:slug>/', views.thread, name='thread'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    path('cursos/', include('simplemooc.courses.urls', namespace='courses')),
    path('forum/', include('simplemooc.forum.urls', namespace='forum')),
    path('admin/', admin.site.urls),
]

# Se estiver em debug...
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # ...a variável vai receber mais uma chamada de função que recebe primeiro uma configuração de URL...
    # que depois vai gerar uma 'view', que recebe uma 'url' que vai pegar o diretório base, e conforme o resto...
    # da 'url' que foi retornado, ele vai buscar o caminho do arquivo.
    # 'MEDIA_ROOT' será o diretório base para todos os arquivos de média de todos os 'Models'...
    # O 'upload_to' é o sufixo, assim o caminho final será o 'MEDIA_ROOT' + 'upload_to'.

# ^ - começo de uma string.
# $ - final de uma string.

simplemooc/forum/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from taggit.managers import TaggableManager


# Justamente o tópico do fórum.
class Thread(models.Model):
    # Título do tópico.
    title = models.CharField('Título', max_length=100)

    # 'SlugField' por padrão cria com um 'index' no banco de dados para indexar.
    # A tendência é que seja único, mas ele não especifica que tem que ser.
    slug = models.SlugField('Identificador', max_length=100, unique=True)

    # Corpo da mensagem.
    body = models.TextField('Mensagem')
    author = models.ForeignKey(
        # Tem que ser colocado dessa forma para que o Django fique
        # compátivel, caso eu altere um modelo que é o usuário.
        settings.AUTH_USER_MODEL,
        verbose_name='Autor',
        # A partir do momento que o tópico tem uma referência para o 'autor', o 'related_name'
        # vai ser uma referência no 'autor' para todos os tópicos que ele criou, ou seja o
        # Django vai criar um atributo dinâmico do usuário, chamado 'threads', e quando
        # acessado a partir de uma instância de um usuário, ele vai referênciar todos
        # os tópicos criados pelo 'usuário'.
        related_name='threads',
        # 'on_delete' é obrigatório no Django 2.0.
        on_delete=models.CASCADE
    )
    # Forma de contabilizar as visualizações.
    views = models.IntegerField('Visualizações', blank=True, default=0)
    # Facilita na hora de ordenar os tópicos.
    answers = models.IntegerField('Respostas', blank=True, default=0)

    tags = TaggableManager()

    # 'auto_now_add' pega a data que criou.
    created = models.DateTimeField('Criado em', auto_now_add=True)
    # 'auto_now' pega a data que alterou.
    modified = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.title

    # Pega a 'tupla' e usa uma função chamada 'reverse' que está no
    # pacote: "from django.core.urlresolvers import reverse",
    # é uma forma de resgatar a 'url' dado um nome. E com isso ele retonar a 'url'.
    # @models.permalink  # deprecated
    def get_absolute_url(self):
        """
        'método' que retorna uma 'tupla'

        # Quando usa esse 'decorator', não precisa indicar o caminho da 'url'.
        Só precisa indicar uma 'tupla' de três valores:
            - 1º é o nome da 'url',
            - 2º os parâmetros posicionais e o
            - 3º é um dicionário com os parâmetros nomeados.
        """
        # return 'forum:thread', (), {'slug': self.slug}  # deprecated
        return reverse('forum:thread', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Tópico'
        verbose_name_plural = 'Tópicos'
        ordering = ['-modified']


class Reply(models.Model):
    thread = models.ForeignKey(
        Thread, verbose_name='Tópico',
        related_name='replies',
        # 'on_delete' é obrigatório no Django 2.0.
        on_delete=models.CASCADE
    )
    # Título do tópico.
    reply = models.TextField('Resposta', max_length=500)
    author = models.ForeignKey(
        # Tem que ser colocado dessa forma para que o Django fique
        # compátivel, caso eu altere um modelo que é o usuário.
        settings.AUTH_USER_MODEL,
        verbose_name='Autor',
        related_name='replies',
        # 'on_delete' é obrigatório no Django 2.0.
        on_delete=models.CASCADE
    )
    correct = models.BooleanField('Correta?', blank=True, default=False)

    # 'auto_now_add' pega a data que criou.
    created = models.DateTimeField('Criado em', auto_now_add=True)
    # 'auto_now' pega a data que alterou.
    modified = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        # Retorna as 100 primeiras letras.
        return self.reply[:100]

    class Meta:
        verbose_name = 'Resposta'
        verbose_name_plural = 'Respostas'
        # O valor booleano 'True' é maior que o 'False', então tem que ser
        # ordenado de forma 'decrescente'. E os outos ordenam pela data.
        ordering = ['-correct', 'created']


def post_save_reply(created, instance, **kwargs):
    # Carrega a quantidade de resposta no tópico.
    instance.thread.answers = instance.thread.replies.count()
    instance.thread.save()

    # toda vez que salvo a resposta, ele verifica se a resposta é uma resposta correta.
    if instance.correct:
        # Ele pega a instância, que é a resposta, pega a 'thread' em questão, busca todas as resposta...
        # ...e faz um filtro excluindo ela própria. Isso funciona porque o 'update' não chama o 'signal'
        # tanto do 'post_save', quanto do 'pre_save'. O 'pre_save' e o 'post_save', são executados apenas
        # no método '.save()', quando você executa de fato uma instância '.save()', o 'update'
        # não dispara esse gatilho.
        instance.thread.replies.exclude(pk=instance.pk).update(correct=False)


def post_deleate_reply(instance, **kwargs):
    instance.thread.answers = instance.thread.replies.count()
    instance.thread.save()


# É importante colocar o 'sender', porque só vai disparar quando for o 'model' 'Reply',
# se não colocar o 'sender', ele vai disprar para qualquer 'model'. Por causa que as
# vezes o 'signal' pode ser carregado duas vezes caso esse arquivo seja importado mais
# de uma vez. E o 'dispatch_uid' é um verificador único.
models.signals.post_save.connect(post_save_reply, sender=Reply, dispatch_uid='post_save_reply')
models.signals.post_delete.connect(post_deleate_reply, sender=Reply, dispatch_uid='post_deleate_reply')

# # Sistema de 'sinais' que o Django criou e já implementou para os modelos,
# # sempre que um modelo for atualizado, ele dispara um 'sinal', e você pode
# # criar uma função e associar a esse 'sinal'. Sempre colocar o '**kwargs'
# # nessa função, porque esse 'post_save' recebe muitos parâmetros.
# def post_save_reply(created, instance, **kwargs):
# 	# todas as vezes que eu criar uma resposta, eu aumento o número do atributo resposta da 'thread'.
# 	if created:
# 		instance.thread.answers = instance.thread.answers + 1
# 		instance.thread.save()
#
# # Porque, toda vez que uma instância for removida, uma reposta for removida,
# # a ideia é que faça essa mesma lógica, só que ao contrário.
# def post_deleate_reply(instance, **kwargs):
# 	instance.thread.answers = instance.thread.answers - 1
# 	instance.thread.save()

simplemooc/forum/forms.py
from django import forms
from simplemooc.forum.models import Reply


class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ['reply']

simplemooc/forum/views.py
import json

from django.shortcuts import redirect, get_object_or_404
from django.views.generic import View, ListView, DetailView
from django.contrib import messages
from django.http import HttpResponse

from .models import Thread, Reply
from .forms import ReplyForm


# class ForumView(View):
#
# 	# template_name = 'forum/index.html'
#    	def get(self, request, *args, **kwargs):
# 		return render(request, 'forum/index.html')
#
#
# class ForumView(TemplateView):
#
# 	# template_name = 'forum/index.html'


class ForumView(ListView):
    # Na listagem indicamos o 'model', mas podemos indicar a 'queryset'.
    # model = Thread
    paginate_by = 10
    template_name = 'forum/index.html'

    # Uma das opções de customização do 'ListView'.
    def get_queryset(self):
        # Quando indica o 'model', ele faz isso 'Thread.objects.all()'.
        queryset = Thread.objects.all()

        # Procura o parâmetro. Quando faço uma 'view' baseada em função,
        # o objeto 'request' sempre estará disponível na função, quando faço
        # em 'classe', esse objeto estará disponível na instância.
        # if 'order' in self.request.GET:

        # Pode ser que o parâmetro 'order' não exista, então pode dar erro,
        # então a 'string' vazia ('') é o valor default.
        order = self.request.GET.get('order', '')

        if order == 'views':
            queryset = queryset.order_by('-views')
        elif order == 'answers':
            queryset = queryset.order_by('-answers')

        # A 'url' que acessar a 'view' 'ForumView' ela é a 'url' que tem o parâmetro nomeado.
        tag = self.kwargs.get('tag', '')

        if tag:
            queryset = queryset.filter(tags__slug__icontains=tag)  # filtra as 'tags' que o 'slug' contém.

        return queryset


def get_context_data(self, **kwargs):
    # 'super' pegar os '**kwargs' e joga no 'contexto', esse '**kwargs' são argumentos que passa na 'url'.
    context = super(ForumView, self).get_context_data(**kwargs)

    # Não estou chamando uma instância, quando chamo uma instância, o 'tags' é
    # filtrado pelos valores que aquela instância tem, quando chamo pela classe,
    # ele chama todos as 'tags' associadas a alguma instância dessa classe.
    context['tags'] = Thread.tags.all()
    return context


class ThreadView(DetailView):
    model = Thread
    template_name = 'forum/thread.html'

    def get(self, request, *args, **kwargs):
        # Quando chama o 'get' ele vai criar o 'self.object', que é justamente a 'thread' em questão.
        response = super(ThreadView, self).get(request, *args, **kwargs)

        # Se o usuário não estiver autenticado, ou ele estiver,
        # Mas não é o 'autor' do tópico, então vai contar uma visualização.
        if not self.request.user.is_authenticated or (self.object.author != self.request.user):
            self.object.views = self.object.views + 1
            self.object.save()

        return response

    def get_context_data(self, **kwargs):
        # Implementa o 'get_context_data()' associado ao 'DetailView'.
        context = super(ThreadView, self).get_context_data(**kwargs)
        context['tags'] = Thread.tags.all()

        # Quando chamar o 'form.is_valid', ele retorna 'valido' apenas se os dados
        # do formulário foram preenchidos, e se preenchidos, são 'válidos'.
        # Os dados do 'form.is_valid' vai retornar 'False',
        context['form'] = ReplyForm(self.request.POST or None)

        # Quando os dados do formulário não foram preenchidos, ou foram,
        # mas não são válidos. Essa diferença é importante, porque quando
        # eu faço uma requisição 'GET' então o 'POST' ele é vazio, mas ele
        # ainda vai tentar validar esses dados, pois ele é um dicionário.
        # Com essa lógica, eu indico, quando o 'POST' for vazio, eu não vou
        # retornar o formulário 'POST' com um dicionário vazio, ele vai retonar
        # a palavra 'None', e a implementação desse 'is_valid', ele verifica,
        # quando for 'None', ou seja, eu não submeti o formulário, que só vai
        # ser submetido quando de fato o método for o 'request.POST'.
        return context

    # Cógdigo do 'get' que o 'DetailView' implementa. Esse método 'post',
    # só é executado no método 'POST', ou seja, o método do 'POST' da
    # função 'ThreadView' só vai ser ativado, quando eu acessar
    # essa 'view' através do método 'POST'.
    def post(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(self.request, 'Para responder ao tópico é necessário estar logado')
            # Redireciona para a mesma 'url', objeto 'request' tem um
            # atributo chamado 'path' que é justamanete a 'url' atual.
            return redirect(self.request.path)

        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        form = context['form']

        if form.is_valid():
            # O 'ModelForm' tem o método 'save', diferente do 'form' normal,
            # porque esse método 'save' vai salvar o objeto. Quando coloco
            # o 'commit=False', eu indico ao 'ModelForm', que o método 'save'
            # não deve salvar o objeto de fato, só deve preencher os dados
            # do formulário no objeto.
            reply = form.save(commit=False)
            reply.thread = self.object
            reply.author = self.request.user
            reply.save()
            messages.success(self.request, 'A sua resposta foi enviada com sucesso')
            context['form'] = ReplyForm()

        # 'render_to_response' bem parecido com o 'render', a diferença é que só passa o contexto.
        # O 'request' já está acessível através de 'self.request', e o template, é o 'template_name'.
        return self.render_to_response(context)


class ReplyCorrectView(View):
    correct = True

    def get(self, request, pk):
        # Tenta pegar a resposta que tem a chave, questão de segurança, pega apenas se for
        # o autor da 'thread'. os dois undescore '__', vai tentar buscar um atributo do
        # campo que é chave estrangeira do modelo atual.
        reply = get_object_or_404(Reply, pk=pk, thread__author=request.user)
        reply.correct = self.correct
        reply.save()
        message = 'Resposta atualizada com sucesso'

        # Essa 'request' tem esse método, que pode verificar se a requisição é 'ajax'.
        if request.is_ajax():
            data = {'success': True, 'message': message}

            # Não vai ser mais aquele 'html/plantext', ou algo desse tipo, vai ser 'application/json'.
            # 'content_type' é importante para o 'browser' saber que tipo está retornando.
            return HttpResponse(json.dumps(data), content_type='application/json')
        else:
            messages.success(request, message)

            # definimos no model de 'forum', o 'get_absolute_url' para a 'thread' em específico.
            return redirect(reply.thread.get_absolute_url())


# 'index' recebe o resultado de 'ForumView.as_view()' o 'as_view' retorna uma função.
index = ForumView.as_view()

# A variável 'thread' vai receber a 'ThreadView' que é uma classe, transformada em função. Uma função em 'view'.
thread = ThreadView.as_view()
reply_correct = ReplyCorrectView.as_view()

# Quando eu uso o 'as_view', eu posso passar parâmetros nomeados,
# eles vão virar os atributos dessa classe, vão substitruir valores.
reply_incorrect = ReplyCorrectView.as_view(correct=False)

# também poderia ter sido declarada dessa forma.
# index = TemplateView.as_view(template_name='forum/index.html')

simplemooc/forum/templates/forum/index.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            <li><a href="{% url 'core:home' %}">Início</a></li>
            <li>/</li>
            <li><a href="{% url 'forum:index' %}">Fórum de Discussões</a></li>
            <li>/</li>
            <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Tópicos do Fórum
                </li>
                <li>
                    <a href="?order=">
                        <i class="fa fa-refresh"></i>
                        Mais Recentes
                    </a>
                </li>
                <li>
                    <a href="?order=views">
                        <i class="fa fa-eye"></i>
                        Mais Visualizados
                    </a>
                </li>
                <li>
                    <a href="?order=answers">
                        <i class="fa fa-comments-o"></i>
                        Mais Comentados
                    </a>
                </li>
                <li class="pure-menu-heading">Tags</li>
                <li>
                    {% for tag in tags %}
                    <a href="{% url 'forum:index_tagged' tag.slug %}" class="tags">
                        <i class="fa fa-tag"></i>
                        {{ tag }}
                    </a>
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% for thread in object_list %}		{# a 'ListView' vai nos fornecer um valor chamado 'object_list', que é justamente a lista de modelos, instâncias, que serve para a página atual, já que colocamos paginação, se não, seriam todos os objetos. #}
            <div class="well">
                <h3><a href="{{ thread.get_absolute_url }}" title="">{{ thread.title }}</a></h3>
                <h5>
                    Criado por {{ thread.author }} | {{ thread.answers }} resposta{{ thread.answers|pluralize }} | {{ thread.views }} Visualizaç{{ thread.views|pluralize:"ão,ões" }} 
                </h5>
                <p>
                    <i class="fa fa-tags"></i>
                    Tags: 
                    {% for tag in thread.tags.all %}	{# lista todas as 'tags'. #}
                    <a href="" title="">{{ tag }}</a>{% if not forloop.last %},{% endif %}		{# 'forloop.last' ele não coloca ',' para o último. #}
                    {% endfor %}
                    <a class="fright" href="{{ thread.get_absolute_url }}" title="">Atualizado a {{ thread.modified|timesince }} atrás</a>
                </p>
            </div>
            {% endfor %}
            <ul class="pagination pagination-centered">
                {% if page_obj.has_previous %}		{# se tem uma página anterior, ao invés do número da página, vai colocar 'Anterior'. #}
                <li>
                    <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">Anterior</a>
                </li>
                {% endif %}
                {% for page in paginator.page_range %}
                <li{% if page == page_obj.number %} class="active"{% endif %}>		{# se ativo, alterar cor da página. #}
                    <a href="?page={{ page }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">{{ page }}</a>
                </li>
                {% endfor %}
                {% if page_obj.has_next %}		{# se tem uma próxima página, ao invés do número da página, vai colocar 'Próxima'. #}
                <li>
                    <a href="?page={{ page_obj.next_page_number }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">Próxima</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

simplemooc/forum/templates/forum/thread.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            <li><a href="{% url 'core:home' %}">Início</a></li>
            <li>/</li>
            <li><a href="{% url 'forum:index' %}">Fórum de Discussões</a></li>
            <li>/</li>
            <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Tópicos do Fórum
                </li>
                <li>
                    <a href="?order=">
                        <i class="fa fa-refresh"></i>
                        Mais Recentes
                    </a>
                </li>
                <li>
                    <a href="?order=views">
                        <i class="fa fa-eye"></i>
                        Mais Visualizados
                    </a>
                </li>
                <li>
                    <a href="?order=answers">
                        <i class="fa fa-comments-o"></i>
                        Mais Comentados
                    </a>
                </li>
                <li class="pure-menu-heading">Tags</li>
                <li>
                    {% for tag in tags %}
                    <a href="{% url 'forum:index_tagged' tag.slug %}" class="tags">
                        <i class="fa fa-tag"></i>
                        {{ tag }}
                    </a>
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            <div class="well">
                <h2>{{ object }}</h2>
                {{ object.body|linebreaks }}
                <h5>
                    Criado por {{ object.author }}
                </h5>
                <p>
                    <i class="fa fa-tags"></i>
                    {% for tag in object.tags.all %}
                    <a href="{% url 'forum:index_tagged' tag.slug %}" title="">{{ tag }}</a>{% if not forloop.last %},{% endif %}
                    {% endfor %}
                    <a class="fright" href="" title="">Criado a {{ object.created|timesince }} atrás</a>
                </p>
            </div>
            <div class="well" id="#div-comments">
                <h4 id="comments">Respostas
                <a class="fright" href="#add_comment">Responder</a></h4>
                {% for reply in object.replies.all %}       {# quando estiver com uma 'thread' em questão, eu posso chamar o atributo 'replies' e automaticamente eu vou chamar todos as respostas que estão associadas com a devida 'thread'. #}
                <hr />
                {#{% filter linebreaks  %}#}
                <p>
                    <strong>{{ reply.author }}</strong> disse à {{ reply.created|timesince }} atrás:
                    <br />
                    {{ reply.reply|linebreaksbr }}
                    <br />
                    {#{% if reply.correct %}#}
                    {% if object.author == user %}       {# verificar se é o autor do tópico. #}
                    {#{% if reply.author == user %}       {# se for o autor da resposta, eu vou indicar que ele possa, cancelar a resposta, ou marcar como correta. #}
                    <a href="{% url 'forum:reply_incorrect' reply.pk %}" title="" class="pure-button button-error reply-cancel-correct-lnk{% if not reply.correct %} hidden{% endif %}">Cancelar Resposta Correta</a>    {# se a resposta não for correta, não vai aparecer esse botão. #}

                    <a href="{% url 'forum:reply_correct' reply.pk %}" title="" class="pure-button button-success reply-correct-lnk{% if reply.correct %} hidden{% endif %}">Resposta Correta</a>   {# se a resposta for correta, não vai aparecer esse botão, aparece o de cima. #}

                    <span class="fright label-success reply-correct-msg{% if not reply.correct %} hidden{% endif %}">resposta indicada pelo autor</span>
                    {#{% endif %}#}
                    <br class="reply-correct-msg{% if not reply.correct %} hidden{% endif %}" />
                    {#{% elif reply.author == user %}#}
                    {% elif reply.correct %}
                    <span class="fright label-success">resposta indicada pelo autor</span>
                    <br />
                    {% endif %}
                </p>
                {#{% endfilter %}#}
                {% endfor %}
                <hr />
                <form method="post" class="pure-form pure-form-stacked" id="add_comment">
                    <fieldset>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="pure-control-group"> 
                            {{ field.label_tag }}
                            {{ field }}
                            {{ fiels.errors }}
                        </div>
                        {% endfor %}
                        <div class="pure-controls">
                            <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(".reply-cancel-correct-lnk").on("click", function(e) {    // pega todos os elementos que tiver 'reply-cancel-correct-lnk'.
        e.preventDefault();     // cancela o evento.
        var $this = $(this);    // cria o objeto 'json' com o 'this', só para poder facilitar a vida.
        var $p = $this.closest("p");     // pega o parágrafo que engloba a resposta.
        $.get($this.attr('href'), function(data) {      // faz a requisição via 'get ajax'.
            if(data.success) {      // se os dados retornados forem um 'json' e forem 'sucesso', tiver a variável 'success == True'.
                $p.find(".reply-correct-msg").addClass('hidden');       // esconde a mensagem de 'reply-correct-msg'.
                $this.addClass('hidden');       // esconde o botão de cancelar a resposta.
                $p.find('.reply-correct-lnk').removeClass('hidden');        // e deixa o botão de indicar a resposta correta, deixa ele visível.
            } else {        // se der algum tipo de erro, se não for 'success'.
                alert(data.message);        // da um alerta.
            }
        }, 'json');
        return false;        // pode ser colocado o return ou o 'e.preventDefault()', os dois cancela o evento.
    });
    $('.reply-correct-lnk').on('click', function(e) {
        e.preventDefault();
        var $this = $(this);    // cria o objeto 'json' com o 'this', só para poder facilitar a vida.
        var $p = $this.closest("p");     // pega o parágrafo que engloba a resposta.
        $.get($this.attr('href'), function(data) {
            if(data.success) {
                $("#div-comments .reply-correct-msg").addClass('hidden');     // supondo que já tenha algumas respostas corretas antes, primeiro esconde todas.
                $("#div-comments .reply-cancel-correct-lnk").addClass('hidden');     // se houver uma resposta correta antes, o 'reply-cancel-correct-lnk' estava visível, então adiciona o 'hidden' e ele não fica visível.
                $("#div-comments .reply-correct-lnk").removeClass('hidden');     // se houver uma resposta antes, esse 'reply-correct-lnk' não estava visível, então agora remove a classe 'hidden', e ele fica visível.

                $p.find(".reply-correct-msg").removeClass('hidden');       // remove a classe 'hidden' da resposta atual. Para apenas ela ficar visível.
                $this.addClass('hidden');       // adiciona a classe 'hidden' para esse elemento, que é o 'reply-correct-lnk'.
                $p.find('.reply-cancel-correct-lnk').removeClass('hidden');        // remove a classe 'hidden' para o botão 'reply-cancel-correct-lnk' poder ser exibido.
            } else {
                alert(data.message);
            }
        }, 'json');
        return false;
    });
</script>
{% endblock %}